// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: Bidirectional.proto
#ifndef GRPC_Bidirectional_2eproto__INCLUDED
#define GRPC_Bidirectional_2eproto__INCLUDED

#include "Bidirectional.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace bidirectional {

class Bidirectional final {
 public:
  static constexpr char const* service_full_name() {
    return "bidirectional.Bidirectional";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // A Bidirectional streaming RPC.
    //
    // Accepts a stream of Message sent while a route is being traversed,
    std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::bidirectional::Message, ::bidirectional::Message>> GetServerResponse(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::bidirectional::Message, ::bidirectional::Message>>(GetServerResponseRaw(context));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::bidirectional::Message, ::bidirectional::Message>> AsyncGetServerResponse(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::bidirectional::Message, ::bidirectional::Message>>(AsyncGetServerResponseRaw(context, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::bidirectional::Message, ::bidirectional::Message>> PrepareAsyncGetServerResponse(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::bidirectional::Message, ::bidirectional::Message>>(PrepareAsyncGetServerResponseRaw(context, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // A Bidirectional streaming RPC.
      //
      // Accepts a stream of Message sent while a route is being traversed,
      virtual void GetServerResponse(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::bidirectional::Message,::bidirectional::Message>* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientReaderWriterInterface< ::bidirectional::Message, ::bidirectional::Message>* GetServerResponseRaw(::grpc::ClientContext* context) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::bidirectional::Message, ::bidirectional::Message>* AsyncGetServerResponseRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::bidirectional::Message, ::bidirectional::Message>* PrepareAsyncGetServerResponseRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    std::unique_ptr< ::grpc::ClientReaderWriter< ::bidirectional::Message, ::bidirectional::Message>> GetServerResponse(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriter< ::bidirectional::Message, ::bidirectional::Message>>(GetServerResponseRaw(context));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::bidirectional::Message, ::bidirectional::Message>> AsyncGetServerResponse(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::bidirectional::Message, ::bidirectional::Message>>(AsyncGetServerResponseRaw(context, cq, tag));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::bidirectional::Message, ::bidirectional::Message>> PrepareAsyncGetServerResponse(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::bidirectional::Message, ::bidirectional::Message>>(PrepareAsyncGetServerResponseRaw(context, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void GetServerResponse(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::bidirectional::Message,::bidirectional::Message>* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientReaderWriter< ::bidirectional::Message, ::bidirectional::Message>* GetServerResponseRaw(::grpc::ClientContext* context) override;
    ::grpc::ClientAsyncReaderWriter< ::bidirectional::Message, ::bidirectional::Message>* AsyncGetServerResponseRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReaderWriter< ::bidirectional::Message, ::bidirectional::Message>* PrepareAsyncGetServerResponseRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_GetServerResponse_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // A Bidirectional streaming RPC.
    //
    // Accepts a stream of Message sent while a route is being traversed,
    virtual ::grpc::Status GetServerResponse(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::bidirectional::Message, ::bidirectional::Message>* stream);
  };
  template <class BaseClass>
  class WithAsyncMethod_GetServerResponse : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetServerResponse() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_GetServerResponse() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetServerResponse(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::bidirectional::Message, ::bidirectional::Message>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetServerResponse(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::bidirectional::Message, ::bidirectional::Message>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(0, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_GetServerResponse<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_GetServerResponse : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetServerResponse() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackBidiHandler< ::bidirectional::Message, ::bidirectional::Message>(
            [this](
                   ::grpc::CallbackServerContext* context) { return this->GetServerResponse(context); }));
    }
    ~WithCallbackMethod_GetServerResponse() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetServerResponse(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::bidirectional::Message, ::bidirectional::Message>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerBidiReactor< ::bidirectional::Message, ::bidirectional::Message>* GetServerResponse(
      ::grpc::CallbackServerContext* /*context*/)
      { return nullptr; }
  };
  typedef WithCallbackMethod_GetServerResponse<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_GetServerResponse : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetServerResponse() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_GetServerResponse() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetServerResponse(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::bidirectional::Message, ::bidirectional::Message>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetServerResponse : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetServerResponse() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_GetServerResponse() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetServerResponse(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::bidirectional::Message, ::bidirectional::Message>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetServerResponse(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(0, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetServerResponse : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetServerResponse() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackBidiHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context) { return this->GetServerResponse(context); }));
    }
    ~WithRawCallbackMethod_GetServerResponse() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetServerResponse(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::bidirectional::Message, ::bidirectional::Message>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerBidiReactor< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* GetServerResponse(
      ::grpc::CallbackServerContext* /*context*/)
      { return nullptr; }
  };
  typedef Service StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef Service StreamedService;
};

}  // namespace bidirectional


#endif  // GRPC_Bidirectional_2eproto__INCLUDED
