// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: clientstreaming.proto
#ifndef GRPC_clientstreaming_2eproto__INCLUDED
#define GRPC_clientstreaming_2eproto__INCLUDED

#include "clientstreaming.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace clientstreaming {

class ClientStreaming final {
 public:
  static constexpr char const* service_full_name() {
    return "clientstreaming.ClientStreaming";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // A Client streaming RPC.
    std::unique_ptr< ::grpc::ClientWriterInterface< ::clientstreaming::Message>> GetServerResponse(::grpc::ClientContext* context, ::clientstreaming::Number* response) {
      return std::unique_ptr< ::grpc::ClientWriterInterface< ::clientstreaming::Message>>(GetServerResponseRaw(context, response));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::clientstreaming::Message>> AsyncGetServerResponse(::grpc::ClientContext* context, ::clientstreaming::Number* response, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::clientstreaming::Message>>(AsyncGetServerResponseRaw(context, response, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::clientstreaming::Message>> PrepareAsyncGetServerResponse(::grpc::ClientContext* context, ::clientstreaming::Number* response, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::clientstreaming::Message>>(PrepareAsyncGetServerResponseRaw(context, response, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // A Client streaming RPC.
      virtual void GetServerResponse(::grpc::ClientContext* context, ::clientstreaming::Number* response, ::grpc::ClientWriteReactor< ::clientstreaming::Message>* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientWriterInterface< ::clientstreaming::Message>* GetServerResponseRaw(::grpc::ClientContext* context, ::clientstreaming::Number* response) = 0;
    virtual ::grpc::ClientAsyncWriterInterface< ::clientstreaming::Message>* AsyncGetServerResponseRaw(::grpc::ClientContext* context, ::clientstreaming::Number* response, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncWriterInterface< ::clientstreaming::Message>* PrepareAsyncGetServerResponseRaw(::grpc::ClientContext* context, ::clientstreaming::Number* response, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    std::unique_ptr< ::grpc::ClientWriter< ::clientstreaming::Message>> GetServerResponse(::grpc::ClientContext* context, ::clientstreaming::Number* response) {
      return std::unique_ptr< ::grpc::ClientWriter< ::clientstreaming::Message>>(GetServerResponseRaw(context, response));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriter< ::clientstreaming::Message>> AsyncGetServerResponse(::grpc::ClientContext* context, ::clientstreaming::Number* response, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncWriter< ::clientstreaming::Message>>(AsyncGetServerResponseRaw(context, response, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriter< ::clientstreaming::Message>> PrepareAsyncGetServerResponse(::grpc::ClientContext* context, ::clientstreaming::Number* response, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncWriter< ::clientstreaming::Message>>(PrepareAsyncGetServerResponseRaw(context, response, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void GetServerResponse(::grpc::ClientContext* context, ::clientstreaming::Number* response, ::grpc::ClientWriteReactor< ::clientstreaming::Message>* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientWriter< ::clientstreaming::Message>* GetServerResponseRaw(::grpc::ClientContext* context, ::clientstreaming::Number* response) override;
    ::grpc::ClientAsyncWriter< ::clientstreaming::Message>* AsyncGetServerResponseRaw(::grpc::ClientContext* context, ::clientstreaming::Number* response, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncWriter< ::clientstreaming::Message>* PrepareAsyncGetServerResponseRaw(::grpc::ClientContext* context, ::clientstreaming::Number* response, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_GetServerResponse_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // A Client streaming RPC.
    virtual ::grpc::Status GetServerResponse(::grpc::ServerContext* context, ::grpc::ServerReader< ::clientstreaming::Message>* reader, ::clientstreaming::Number* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_GetServerResponse : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetServerResponse() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_GetServerResponse() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetServerResponse(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::clientstreaming::Message>* /*reader*/, ::clientstreaming::Number* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetServerResponse(::grpc::ServerContext* context, ::grpc::ServerAsyncReader< ::clientstreaming::Number, ::clientstreaming::Message>* reader, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncClientStreaming(0, context, reader, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_GetServerResponse<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_GetServerResponse : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetServerResponse() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackClientStreamingHandler< ::clientstreaming::Message, ::clientstreaming::Number>(
            [this](
                   ::grpc::CallbackServerContext* context, ::clientstreaming::Number* response) { return this->GetServerResponse(context, response); }));
    }
    ~WithCallbackMethod_GetServerResponse() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetServerResponse(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::clientstreaming::Message>* /*reader*/, ::clientstreaming::Number* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerReadReactor< ::clientstreaming::Message>* GetServerResponse(
      ::grpc::CallbackServerContext* /*context*/, ::clientstreaming::Number* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_GetServerResponse<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_GetServerResponse : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetServerResponse() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_GetServerResponse() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetServerResponse(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::clientstreaming::Message>* /*reader*/, ::clientstreaming::Number* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetServerResponse : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetServerResponse() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_GetServerResponse() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetServerResponse(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::clientstreaming::Message>* /*reader*/, ::clientstreaming::Number* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetServerResponse(::grpc::ServerContext* context, ::grpc::ServerAsyncReader< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* reader, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncClientStreaming(0, context, reader, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetServerResponse : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetServerResponse() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackClientStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, ::grpc::ByteBuffer* response) { return this->GetServerResponse(context, response); }));
    }
    ~WithRawCallbackMethod_GetServerResponse() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetServerResponse(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::clientstreaming::Message>* /*reader*/, ::clientstreaming::Number* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerReadReactor< ::grpc::ByteBuffer>* GetServerResponse(
      ::grpc::CallbackServerContext* /*context*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  typedef Service StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef Service StreamedService;
};

}  // namespace clientstreaming


#endif  // GRPC_clientstreaming_2eproto__INCLUDED
