// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: hello_grpc.proto
#ifndef GRPC_hello_5fgrpc_2eproto__INCLUDED
#define GRPC_hello_5fgrpc_2eproto__INCLUDED

#include "hello_grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace hello_grpc {

class MyService final {
 public:
  static constexpr char const* service_full_name() {
    return "hello_grpc.MyService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status MyFunction(::grpc::ClientContext* context, const ::hello_grpc::MyNumber& request, ::hello_grpc::MyNumber* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::hello_grpc::MyNumber>> AsyncMyFunction(::grpc::ClientContext* context, const ::hello_grpc::MyNumber& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::hello_grpc::MyNumber>>(AsyncMyFunctionRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::hello_grpc::MyNumber>> PrepareAsyncMyFunction(::grpc::ClientContext* context, const ::hello_grpc::MyNumber& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::hello_grpc::MyNumber>>(PrepareAsyncMyFunctionRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void MyFunction(::grpc::ClientContext* context, const ::hello_grpc::MyNumber* request, ::hello_grpc::MyNumber* response, std::function<void(::grpc::Status)>) = 0;
      virtual void MyFunction(::grpc::ClientContext* context, const ::hello_grpc::MyNumber* request, ::hello_grpc::MyNumber* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::hello_grpc::MyNumber>* AsyncMyFunctionRaw(::grpc::ClientContext* context, const ::hello_grpc::MyNumber& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::hello_grpc::MyNumber>* PrepareAsyncMyFunctionRaw(::grpc::ClientContext* context, const ::hello_grpc::MyNumber& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status MyFunction(::grpc::ClientContext* context, const ::hello_grpc::MyNumber& request, ::hello_grpc::MyNumber* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::hello_grpc::MyNumber>> AsyncMyFunction(::grpc::ClientContext* context, const ::hello_grpc::MyNumber& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::hello_grpc::MyNumber>>(AsyncMyFunctionRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::hello_grpc::MyNumber>> PrepareAsyncMyFunction(::grpc::ClientContext* context, const ::hello_grpc::MyNumber& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::hello_grpc::MyNumber>>(PrepareAsyncMyFunctionRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void MyFunction(::grpc::ClientContext* context, const ::hello_grpc::MyNumber* request, ::hello_grpc::MyNumber* response, std::function<void(::grpc::Status)>) override;
      void MyFunction(::grpc::ClientContext* context, const ::hello_grpc::MyNumber* request, ::hello_grpc::MyNumber* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::hello_grpc::MyNumber>* AsyncMyFunctionRaw(::grpc::ClientContext* context, const ::hello_grpc::MyNumber& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::hello_grpc::MyNumber>* PrepareAsyncMyFunctionRaw(::grpc::ClientContext* context, const ::hello_grpc::MyNumber& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_MyFunction_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status MyFunction(::grpc::ServerContext* context, const ::hello_grpc::MyNumber* request, ::hello_grpc::MyNumber* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_MyFunction : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_MyFunction() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_MyFunction() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status MyFunction(::grpc::ServerContext* /*context*/, const ::hello_grpc::MyNumber* /*request*/, ::hello_grpc::MyNumber* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestMyFunction(::grpc::ServerContext* context, ::hello_grpc::MyNumber* request, ::grpc::ServerAsyncResponseWriter< ::hello_grpc::MyNumber>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_MyFunction<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_MyFunction : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_MyFunction() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::hello_grpc::MyNumber, ::hello_grpc::MyNumber>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::hello_grpc::MyNumber* request, ::hello_grpc::MyNumber* response) { return this->MyFunction(context, request, response); }));}
    void SetMessageAllocatorFor_MyFunction(
        ::grpc::MessageAllocator< ::hello_grpc::MyNumber, ::hello_grpc::MyNumber>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::hello_grpc::MyNumber, ::hello_grpc::MyNumber>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_MyFunction() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status MyFunction(::grpc::ServerContext* /*context*/, const ::hello_grpc::MyNumber* /*request*/, ::hello_grpc::MyNumber* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* MyFunction(
      ::grpc::CallbackServerContext* /*context*/, const ::hello_grpc::MyNumber* /*request*/, ::hello_grpc::MyNumber* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_MyFunction<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_MyFunction : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_MyFunction() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_MyFunction() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status MyFunction(::grpc::ServerContext* /*context*/, const ::hello_grpc::MyNumber* /*request*/, ::hello_grpc::MyNumber* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_MyFunction : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_MyFunction() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_MyFunction() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status MyFunction(::grpc::ServerContext* /*context*/, const ::hello_grpc::MyNumber* /*request*/, ::hello_grpc::MyNumber* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestMyFunction(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_MyFunction : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_MyFunction() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->MyFunction(context, request, response); }));
    }
    ~WithRawCallbackMethod_MyFunction() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status MyFunction(::grpc::ServerContext* /*context*/, const ::hello_grpc::MyNumber* /*request*/, ::hello_grpc::MyNumber* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* MyFunction(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_MyFunction : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_MyFunction() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::hello_grpc::MyNumber, ::hello_grpc::MyNumber>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::hello_grpc::MyNumber, ::hello_grpc::MyNumber>* streamer) {
                       return this->StreamedMyFunction(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_MyFunction() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status MyFunction(::grpc::ServerContext* /*context*/, const ::hello_grpc::MyNumber* /*request*/, ::hello_grpc::MyNumber* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedMyFunction(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::hello_grpc::MyNumber,::hello_grpc::MyNumber>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_MyFunction<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_MyFunction<Service > StreamedService;
};

}  // namespace hello_grpc


#endif  // GRPC_hello_5fgrpc_2eproto__INCLUDED
