// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: hello_grpc.proto

#include "hello_grpc.pb.h"
#include "hello_grpc.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace hello_grpc {

static const char* MyService_method_names[] = {
  "/hello_grpc.MyService/MyFunction",
};

std::unique_ptr< MyService::Stub> MyService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< MyService::Stub> stub(new MyService::Stub(channel, options));
  return stub;
}

MyService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_MyFunction_(MyService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status MyService::Stub::MyFunction(::grpc::ClientContext* context, const ::hello_grpc::MyNumber& request, ::hello_grpc::MyNumber* response) {
  return ::grpc::internal::BlockingUnaryCall< ::hello_grpc::MyNumber, ::hello_grpc::MyNumber, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_MyFunction_, context, request, response);
}

void MyService::Stub::async::MyFunction(::grpc::ClientContext* context, const ::hello_grpc::MyNumber* request, ::hello_grpc::MyNumber* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::hello_grpc::MyNumber, ::hello_grpc::MyNumber, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_MyFunction_, context, request, response, std::move(f));
}

void MyService::Stub::async::MyFunction(::grpc::ClientContext* context, const ::hello_grpc::MyNumber* request, ::hello_grpc::MyNumber* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_MyFunction_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::hello_grpc::MyNumber>* MyService::Stub::PrepareAsyncMyFunctionRaw(::grpc::ClientContext* context, const ::hello_grpc::MyNumber& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::hello_grpc::MyNumber, ::hello_grpc::MyNumber, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_MyFunction_, context, request);
}

::grpc::ClientAsyncResponseReader< ::hello_grpc::MyNumber>* MyService::Stub::AsyncMyFunctionRaw(::grpc::ClientContext* context, const ::hello_grpc::MyNumber& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncMyFunctionRaw(context, request, cq);
  result->StartCall();
  return result;
}

MyService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MyService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MyService::Service, ::hello_grpc::MyNumber, ::hello_grpc::MyNumber, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](MyService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::hello_grpc::MyNumber* req,
             ::hello_grpc::MyNumber* resp) {
               return service->MyFunction(ctx, req, resp);
             }, this)));
}

MyService::Service::~Service() {
}

::grpc::Status MyService::Service::MyFunction(::grpc::ServerContext* context, const ::hello_grpc::MyNumber* request, ::hello_grpc::MyNumber* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace hello_grpc

