// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: serverstreaming.proto

#include "serverstreaming.pb.h"
#include "serverstreaming.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace serverstreaming {

static const char* ServerStreaming_method_names[] = {
  "/serverstreaming.ServerStreaming/GetServerResponse",
};

std::unique_ptr< ServerStreaming::Stub> ServerStreaming::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< ServerStreaming::Stub> stub(new ServerStreaming::Stub(channel, options));
  return stub;
}

ServerStreaming::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_GetServerResponse_(ServerStreaming_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  {}

::grpc::ClientReader< ::serverstreaming::Message>* ServerStreaming::Stub::GetServerResponseRaw(::grpc::ClientContext* context, const ::serverstreaming::Number& request) {
  return ::grpc::internal::ClientReaderFactory< ::serverstreaming::Message>::Create(channel_.get(), rpcmethod_GetServerResponse_, context, request);
}

void ServerStreaming::Stub::async::GetServerResponse(::grpc::ClientContext* context, const ::serverstreaming::Number* request, ::grpc::ClientReadReactor< ::serverstreaming::Message>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::serverstreaming::Message>::Create(stub_->channel_.get(), stub_->rpcmethod_GetServerResponse_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::serverstreaming::Message>* ServerStreaming::Stub::AsyncGetServerResponseRaw(::grpc::ClientContext* context, const ::serverstreaming::Number& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::serverstreaming::Message>::Create(channel_.get(), cq, rpcmethod_GetServerResponse_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::serverstreaming::Message>* ServerStreaming::Stub::PrepareAsyncGetServerResponseRaw(::grpc::ClientContext* context, const ::serverstreaming::Number& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::serverstreaming::Message>::Create(channel_.get(), cq, rpcmethod_GetServerResponse_, context, request, false, nullptr);
}

ServerStreaming::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ServerStreaming_method_names[0],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< ServerStreaming::Service, ::serverstreaming::Number, ::serverstreaming::Message>(
          [](ServerStreaming::Service* service,
             ::grpc::ServerContext* ctx,
             const ::serverstreaming::Number* req,
             ::grpc::ServerWriter<::serverstreaming::Message>* writer) {
               return service->GetServerResponse(ctx, req, writer);
             }, this)));
}

ServerStreaming::Service::~Service() {
}

::grpc::Status ServerStreaming::Service::GetServerResponse(::grpc::ServerContext* context, const ::serverstreaming::Number* request, ::grpc::ServerWriter< ::serverstreaming::Message>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace serverstreaming

