// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: serverstreaming.proto
#ifndef GRPC_serverstreaming_2eproto__INCLUDED
#define GRPC_serverstreaming_2eproto__INCLUDED

#include "serverstreaming.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace serverstreaming {

class ServerStreaming final {
 public:
  static constexpr char const* service_full_name() {
    return "serverstreaming.ServerStreaming";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // A Client streaming RPC.
    std::unique_ptr< ::grpc::ClientReaderInterface< ::serverstreaming::Message>> GetServerResponse(::grpc::ClientContext* context, const ::serverstreaming::Number& request) {
      return std::unique_ptr< ::grpc::ClientReaderInterface< ::serverstreaming::Message>>(GetServerResponseRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::serverstreaming::Message>> AsyncGetServerResponse(::grpc::ClientContext* context, const ::serverstreaming::Number& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::serverstreaming::Message>>(AsyncGetServerResponseRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::serverstreaming::Message>> PrepareAsyncGetServerResponse(::grpc::ClientContext* context, const ::serverstreaming::Number& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::serverstreaming::Message>>(PrepareAsyncGetServerResponseRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // A Client streaming RPC.
      virtual void GetServerResponse(::grpc::ClientContext* context, const ::serverstreaming::Number* request, ::grpc::ClientReadReactor< ::serverstreaming::Message>* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientReaderInterface< ::serverstreaming::Message>* GetServerResponseRaw(::grpc::ClientContext* context, const ::serverstreaming::Number& request) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::serverstreaming::Message>* AsyncGetServerResponseRaw(::grpc::ClientContext* context, const ::serverstreaming::Number& request, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::serverstreaming::Message>* PrepareAsyncGetServerResponseRaw(::grpc::ClientContext* context, const ::serverstreaming::Number& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    std::unique_ptr< ::grpc::ClientReader< ::serverstreaming::Message>> GetServerResponse(::grpc::ClientContext* context, const ::serverstreaming::Number& request) {
      return std::unique_ptr< ::grpc::ClientReader< ::serverstreaming::Message>>(GetServerResponseRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::serverstreaming::Message>> AsyncGetServerResponse(::grpc::ClientContext* context, const ::serverstreaming::Number& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::serverstreaming::Message>>(AsyncGetServerResponseRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::serverstreaming::Message>> PrepareAsyncGetServerResponse(::grpc::ClientContext* context, const ::serverstreaming::Number& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::serverstreaming::Message>>(PrepareAsyncGetServerResponseRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void GetServerResponse(::grpc::ClientContext* context, const ::serverstreaming::Number* request, ::grpc::ClientReadReactor< ::serverstreaming::Message>* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientReader< ::serverstreaming::Message>* GetServerResponseRaw(::grpc::ClientContext* context, const ::serverstreaming::Number& request) override;
    ::grpc::ClientAsyncReader< ::serverstreaming::Message>* AsyncGetServerResponseRaw(::grpc::ClientContext* context, const ::serverstreaming::Number& request, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReader< ::serverstreaming::Message>* PrepareAsyncGetServerResponseRaw(::grpc::ClientContext* context, const ::serverstreaming::Number& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_GetServerResponse_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // A Client streaming RPC.
    virtual ::grpc::Status GetServerResponse(::grpc::ServerContext* context, const ::serverstreaming::Number* request, ::grpc::ServerWriter< ::serverstreaming::Message>* writer);
  };
  template <class BaseClass>
  class WithAsyncMethod_GetServerResponse : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetServerResponse() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_GetServerResponse() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetServerResponse(::grpc::ServerContext* /*context*/, const ::serverstreaming::Number* /*request*/, ::grpc::ServerWriter< ::serverstreaming::Message>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetServerResponse(::grpc::ServerContext* context, ::serverstreaming::Number* request, ::grpc::ServerAsyncWriter< ::serverstreaming::Message>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(0, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_GetServerResponse<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_GetServerResponse : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetServerResponse() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackServerStreamingHandler< ::serverstreaming::Number, ::serverstreaming::Message>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::serverstreaming::Number* request) { return this->GetServerResponse(context, request); }));
    }
    ~WithCallbackMethod_GetServerResponse() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetServerResponse(::grpc::ServerContext* /*context*/, const ::serverstreaming::Number* /*request*/, ::grpc::ServerWriter< ::serverstreaming::Message>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::serverstreaming::Message>* GetServerResponse(
      ::grpc::CallbackServerContext* /*context*/, const ::serverstreaming::Number* /*request*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_GetServerResponse<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_GetServerResponse : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetServerResponse() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_GetServerResponse() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetServerResponse(::grpc::ServerContext* /*context*/, const ::serverstreaming::Number* /*request*/, ::grpc::ServerWriter< ::serverstreaming::Message>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetServerResponse : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetServerResponse() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_GetServerResponse() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetServerResponse(::grpc::ServerContext* /*context*/, const ::serverstreaming::Number* /*request*/, ::grpc::ServerWriter< ::serverstreaming::Message>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetServerResponse(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncWriter< ::grpc::ByteBuffer>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(0, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetServerResponse : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetServerResponse() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackServerStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const::grpc::ByteBuffer* request) { return this->GetServerResponse(context, request); }));
    }
    ~WithRawCallbackMethod_GetServerResponse() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetServerResponse(::grpc::ServerContext* /*context*/, const ::serverstreaming::Number* /*request*/, ::grpc::ServerWriter< ::serverstreaming::Message>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::grpc::ByteBuffer>* GetServerResponse(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/)  { return nullptr; }
  };
  typedef Service StreamedUnaryService;
  template <class BaseClass>
  class WithSplitStreamingMethod_GetServerResponse : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithSplitStreamingMethod_GetServerResponse() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::SplitServerStreamingHandler<
          ::serverstreaming::Number, ::serverstreaming::Message>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerSplitStreamer<
                     ::serverstreaming::Number, ::serverstreaming::Message>* streamer) {
                       return this->StreamedGetServerResponse(context,
                         streamer);
                  }));
    }
    ~WithSplitStreamingMethod_GetServerResponse() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetServerResponse(::grpc::ServerContext* /*context*/, const ::serverstreaming::Number* /*request*/, ::grpc::ServerWriter< ::serverstreaming::Message>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with split streamed
    virtual ::grpc::Status StreamedGetServerResponse(::grpc::ServerContext* context, ::grpc::ServerSplitStreamer< ::serverstreaming::Number,::serverstreaming::Message>* server_split_streamer) = 0;
  };
  typedef WithSplitStreamingMethod_GetServerResponse<Service > SplitStreamedService;
  typedef WithSplitStreamingMethod_GetServerResponse<Service > StreamedService;
};

}  // namespace serverstreaming


#endif  // GRPC_serverstreaming_2eproto__INCLUDED
